default_title:  "Inherent Knowledge, LLC"
default_desc:   "Inherent Knowledge is a web design and search engine optimization (SEO) company in Jacksonville, Florida.  Specialties include e-commerce, mobile design, usability design, and responsive websites for small businesses, especially recreational education businesses."
default_canonical:   "www.inherent-knowledge.com"
